<div id="toolbar">
	<ul>
		<li><a href="SimpleSearchPage" title="Simple Free Text and Concept based search"><span style="_MENU_STYLE_SEARCH_">Search</span></a></li>		
		<li><a href="ExploreDataPage" title="Explore your Data by querying using SAPARQL, navigate and visualize your data graph"><span style="_MENU_STYLE_EXPLORE_">Query</span></a></li>
		<li><a href="AdminPage" title="Administer SPARQL endpoints. Login"><span style="_MENU_STYLE_ADMIN_">Home</span></a></li>
		<li><a href="visualize/navigationGraph" title="Navigation Map"><span style="_MENU_STYLE_ADMIN_"><img src="img/tonavmap.png" width="60"/></span></a></li>
		</ul>
</div>
